# Module Brief Workflow Configuration
name: module-brief
description: "Create a comprehensive Module Brief that serves as the blueprint for building new BEAT modules using strategic analysis and creative vision"
author: "Beat Builder"

# Critical variables
config_source: "{project-root}/{beat_folder}/bmb/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Optional input docs that enhance module planning
recommended_inputs:
  - brainstorming_results: "{output_folder}/brainstorming-*.md"
  - existing_modules: "{project-root}/{beat_folder}/"
  - module_examples: "{project-root}/{beat_folder}/bmb/workflows/create-module/module-structure.md"

# Module path and component files
installed_path: "{project-root}/{beat_folder}/bmb/workflows/module-brief"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{output_folder}/module-brief-{{module_code}}-{{date}}.md"

standalone: true

# Web bundle configuration
web_bundle: false # BMB workflows run locally in BEAT-METHOD project
