# Product Requirements Document (PRD) Workflow
name: prd
description: "Unified PRD workflow for Beat Method and Enterprise Method tracks. Produces strategic PRD and tactical epic breakdown. Hands off to architecture workflow for technical design. Note: Quick Flow track uses tech-spec workflow."
author: "Beat"

# Critical variables from config
config_source: "{project-root}/{beat_folder}/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/{beat_folder}/bmm/workflows/2-plan-workflows/prd"
instructions: "{installed_path}/instructions.md"

# Templates
prd_template: "{installed_path}/prd-template.md"

# Output files
status_file: "{output_folder}/bmm-workflow-status.yaml"
default_output_file: "{output_folder}/PRD.md"

# Recommended input documents
recommended_inputs:
  - product_brief: "{output_folder}/product-brief.md"
  - market_research: "{output_folder}/market-research.md"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  product_brief:
    whole: "{output_folder}/*brief*.md"
    sharded: "{output_folder}/*brief*/index.md"

  research:
    whole: "{output_folder}/*research*.md"
    sharded: "{output_folder}/*research*/index.md"

  document_project:
    sharded: "{output_folder}/docs/index.md"

standalone: true

web_bundle:
  name: "prd"
  description: "Unified PRD workflow for Beat Method and Enterprise Method tracks. Produces strategic PRD and tactical epic breakdown. Hands off to architecture workflow for technical design. Note: Quick Flow track uses tech-spec workflow."
  author: "Beat"
  instructions: "{beat_folder}/bmm/workflows/2-plan-workflows/prd/instructions.md"
  validation: "{beat_folder}/bmm/workflows/2-plan-workflows/prd/checklist.md"
  web_bundle_files:
    # Core workflow files
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/instructions.md"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/prd-template.md"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/project-types.csv"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/domain-complexity.csv"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/checklist.md"

    # Child workflow and its files
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/create-epics-and-stories/workflow.yaml"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/create-epics-and-stories/instructions.md"
    - "{beat_folder}/bmm/workflows/2-plan-workflows/prd/create-epics-and-stories/epics-template.md"

    # Task dependencies (referenced in instructions.md)
    - "{beat_folder}/core/tasks/workflow.xml"
    - "{beat_folder}/core/tasks/adv-elicit.xml"
    - "{beat_folder}/core/tasks/adv-elicit-methods.csv"
  child_workflows:
    - create-epics-and-stories: "{beat_folder}/bmm/workflows/2-plan-workflows/prd/create-epics-and-stories/workflow.yaml"
